name: Python Lint

on: [pull_request, push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@master
      with:
          python-root-list: "src"
    - uses: wemake-services/wemake-python-styleguide@master
    
