name: Python Lint

on: [pull_request, push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@test
    - uses: wemake-services/wemake-python-styleguide@master
