name: Python Lint

on: [pull_request, push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
    - uses: ricardochaves/python-lint@master
      with:
          python-root-list: "src"
    - uses: wemake-services/wemake-python-styleguide@master
    
