name: Python Lint

on: [pull_request, push]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        pip install -r "requipments.txt"
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@master
      with:
          python-root-list: "src"
    - uses: wemake-services/wemake-python-styleguide@master
    
