# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Telegram notification

on:
  pull_request:
    branches: [ develop ]
  push:
    branches: [ develop ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs the telegram notify action to send a notification
      - name: Telegram Notify
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN_NOTIF }}
          message: |
            A new PR is raised by ${{ github.actor }}.
            Commit message: ${{ github.event.commits[0].message }} 
            
            View this PR - https://github.com/alex2211-put/bot_assistant_hack/pull/${{ github.event.number }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
